-- Senedd Tracker Supabase schema
-- Initial migration for a fresh Supabase project.

CREATE TABLE IF NOT EXISTS http_cache (
  cache_key text PRIMARY KEY,
  url text NOT NULL,
  status integer NOT NULL,
  response_body text NOT NULL,
  content_type text,
  fetched_at bigint NOT NULL,
  expires_at bigint NOT NULL,
  source text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_http_cache_expires_at ON http_cache(expires_at);

CREATE TABLE IF NOT EXISTS members (
  id text PRIMARY KEY,
  name text NOT NULL,
  party text,
  area_name text,
  area_type text,
  profile_url text,
  image_url text,
  senedd_uid integer,
  updated_at bigint NOT NULL,
  last_updated_at bigint
);

CREATE TABLE IF NOT EXISTS plenary_transcripts (
  meeting_id bigint PRIMARY KEY,
  meeting_date text,
  transcript_url text NOT NULL,
  fetched_at bigint,
  parsed_at bigint,
  parse_version integer NOT NULL,
  last_updated_at bigint
);

CREATE TABLE IF NOT EXISTS plenary_votes (
  meeting_id bigint PRIMARY KEY,
  meeting_date text,
  votes_url text NOT NULL,
  fetched_at bigint,
  parsed_at bigint,
  parse_version integer NOT NULL,
  last_updated_at bigint
);

CREATE TABLE IF NOT EXISTS spoken_contributions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id bigint NOT NULL,
  contribution_id bigint NOT NULL,
  member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  speaker_name text NOT NULL,
  occurred_at text NOT NULL,
  context_en text,
  context_cy text,
  snippet_en text NOT NULL,
  snippet_cy text,
  full_text_en text,
  full_text_cy text,
  source_url text NOT NULL,
  confidence text NOT NULL,
  extracted_at bigint NOT NULL,
  last_updated_at bigint,
  UNIQUE(meeting_id, contribution_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_spoken_contributions_member_id ON spoken_contributions(member_id);
CREATE INDEX IF NOT EXISTS idx_spoken_contributions_occurred_at ON spoken_contributions(occurred_at);

CREATE TABLE IF NOT EXISTS member_votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id bigint NOT NULL,
  contribution_id bigint NOT NULL,
  vote_row_id bigint,
  member_id text NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  member_uid integer,
  member_name text,
  occurred_at text NOT NULL,
  vote_name_en text,
  vote_name_cy text,
  vote_result_en text,
  vote_result_cy text,
  totals_for integer,
  totals_against integer,
  totals_abstain integer,
  member_result text NOT NULL,
  source_url text NOT NULL,
  confidence text NOT NULL,
  extracted_at bigint NOT NULL,
  last_updated_at bigint,
  UNIQUE(meeting_id, contribution_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_member_votes_member_id ON member_votes(member_id);
CREATE INDEX IF NOT EXISTS idx_member_votes_occurred_at ON member_votes(occurred_at);
